spring:
  application:
    name: Application
  config:
    import: 'classpath:document-processor-uploader.yml'

server:
  port: 9000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    syntax-highlight:
      activated: true
    enabled: true
